### ISSUE TITLE
Runtime crash with OMPT and parallel for from kmp_sched.cpp(85)

### ISSUE THREAD

**Issue by yanyh15** [OpenMPToolsInterface/LLVM-openmp#38]
I am not sure whether this is my problem or the bug in the ompt implementation. I knew two persons including me saw the same bug in kmp_sched.cpp(85). 

~~~~
yanyh@vm:~/tools/omptool/examples/simple$ make run
clang -shared -fopenmp -fPIC -I/home/yanyh/tools/llvm-openmp/BUILD/runtime/src -I/home/yanyh/tools/llvm-openmp/runtime/test/ompt empty.c -o libompt.so
clang -fopenmp helloomp.c -o helloomp
LD_PRELOAD=./libompt.so ./helloomp
0: NULL_POINTER=(nil)
281474976710657: ompt_event_thread_begin: thread_type=ompt_thread_initial=1, thread_id=281474976710657
281474976710657: ompt_event_task_create: parent_task_id=0, parent_task_frame.exit=(nil), parent_task_frame.reenter=(nil), new_task_id=281474976710658, codeptr_ra=(nil), task_type=ompt_task_initial=1, has_dependences=no
281474976710657: ompt_event_parallel_begin: parent_task_id=281474976710658, parent_task_frame.exit=(nil), parent_task_frame.reenter=0x7ffe2f5167d0, parallel_id=281474976710660, requested_team_size=4, codeptr_ra=0x400723, invoker=2
281474976710657: ompt_event_implicit_task_begin: parallel_id=281474976710660, task_id=281474976710661, team_size=4, thread_num=0
Assertion failure at kmp_sched.cpp(85): __kmpc_for_static_init: can't determine workshare type.
OMP: Error #13: Assertion failure at kmp_sched.cpp(85).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
562949953421313: ompt_event_thread_begin: thread_type=ompt_thread_worker=2, thread_id=562949953421313
562949953421313: ompt_event_implicit_task_begin: parallel_id=281474976710660, task_id=562949953421314, team_size=4, thread_num=1
Assertion failure at kmp_sched.cpp(85): __kmpc_for_static_init: can't determine workshare type.
Aborted (core dumped)
Makefile:12: recipe for target 'run' failed
make: *** [run] Error 134
~~~~~

The bug was triggered  by the following omp worksharing loop. callback.h file from the runtime/test/ompt folder is used for building the tool. 

~~~
/* helloomp.c file */
#include <stdio.h>
#include <omp.h>

int main(int argc, char* argv[])
 {
   int i;
   int N=100;
   int A[N];
   #pragma omp parallel for
   for (i=0; i<N; i++) {
       A[i] = 8*i;
   }
}
~~~~

The file for building an OMPT tool using callback.h
~~~~
/* empty.c file */
#include "callback.h"
~~~~

clang version is 4.0
~~~~
yanyh@vm:~/tools/omptool/examples/simple$ clang --version
clang version 4.0.0 (http://llvm.org/git/clang.git b1ff58de6ea8a246fa5306cd4228cc8d6141dab5) (http://llvm.org/git/llvm.git c57d1d62952f85678048ab65af49cd1a452e40f7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/yanyh/ompllvm/llvm-official-install/bin
~~~~~~

**Comment by jprotze** [comment]
This implementation is only compatible with latest version of clang. 
We are thinking of potentially fixing it, but the result for a outdated compiler version would be non-conforming behavior, i.e. the callback provided for sections/forloop/... would be the same.

**Comment by yanyh15** [comment]
That was what i thought too. building clang/llvm has been a nightmare, i tried from yesterday multiple times and still did not succeed.

**Comment by jprotze** [comment]
The fixes in the deprecated-workshare branch should make the runtime compatible with outdated caompilers, but it prints a warning.

**Comment by yanyh15** [comment]
@jprotze thank you for that. will give it a try.

**Comment by yanyh15** [comment]
I gave a try. It works with the warning messages. I also able to compile llvm/clang so the latest upstream also works with the latest clang. I however saw the follow error, in both the upstream and the deprecated-workshare  branch. It seems some data racing in the runtime when the openmp runtime is built with debug on, as I do not see the problem every time I run. It could have nothing to do with ompt. I leave the msg here in case in the future we need to revisit or re-file just this as a separate bug. For this issue, I will close. 

~~~
LD_PRELOAD=/home/yanyh/tools/omptool/build/libomptool.so ./axpyclang 1024	
0: NULL_POINTER=(nil)
omptool initialized
======================================================================================================
	AXPY: Y[N] = Y[N] + a*X[N], N=1024, 4 threads for dist
------------------------------------------------------------------------------------------------------
Performance:			Runtime (ms)	 MFLOPS 		Error (compared to base)
------------------------------------------------------------------------------------------------------
axpy_omp_parallel_for:		0.000000	 inf 		-63066.1
Assertion failure at kmp_alloc.cpp(1616): descr.ptr_aligned == ptr.
OMP: Error #13: Assertion failure at kmp_alloc.cpp(1616).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
Aborted (core dumped)
Makefile:33: recipe for target 'run' failed
~~~~

I did quick gdb with backtrace
~~~~
(gdb) bt
#0  0x00007f429f9b6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f429f9b802a in __GI_abort () at abort.c:89
#2  0x00007f429ffb4f96 in __kmp_print_thread_storage_map (thr=0x7f429ffb4f96 <__kmp_print_thread_storage_map(kmp_info_t*, int)+298>, gtid=0)
    at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:474
#3  0x00007f429ffb3d3f in __kmp_vprintf(kmp_io, const char *, typedef __va_list_tag __va_list_tag *) (__kmp_io=kmp_out, 
    format=0x300000001 <error: Cannot access memory at address 0x300000001>, ap=0x7f42a02822dc <__kmp_console_lock+44>)
    at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_io.cpp:168
#4  0x00007f429ffad0fc in __kmp_dump_debug_buffer () at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_debug.cpp:114
#5  0x00007f429ff8adb4 in ___kmp_fast_allocate (this_thr=0x7f4264ed2290, size=139924129269248, 
    _file_=0xbfd90000980 <error: Cannot access memory at address 0xbfd90000980>, _line_=32578) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_alloc.cpp:1650
#6  0x00007f429ffbbb98 in __kmp_reallocate_team_arrays (team=0x7ddc80, max_nth=32764) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:3087
#7  0x00007f429ffc249e in __kmp_free_thread (this_th=0x190000980) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:5530
#8  0x00007f429ffc3131 in __kmp_internal_end () at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:5949
#9  0x00007f429ffc32ec in __kmp_internal_end_library (gtid_req=32) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:6030
#10 0x00007f429ffc3729 in __kmp_internal_end_thread (gtid_req=-1) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:6150
#11 0x00007f429ffc2dbf in __kmp_reap_thread (thread=0x7f42a0289b80 <__kmp_exit_lock+16>, is_root=0) at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:5831
#12 0x00007f429ffc2d83 in __kmp_reap_thread (thread=0x7f429ffc3729 <__kmp_internal_end_thread(int)+224>, is_root=32764)
    at /home/yanyh/tools/llvm-openmp/runtime/src/kmp_runtime.cpp:5826
#13 0x00007f42a04ccde7 in _dl_fini () at dl-fini.c:235
#14 0x00007f429f9baff8 in __run_exit_handlers (status=0, listp=0x7f429fd455f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#15 0x00007f429f9bb045 in __GI_exit (status=<optimized out>) at exit.c:104
#16 0x00007f429f9a1837 in __libc_start_main (main=0x400d50 <check+48>, argc=2, argv=0x7ffca96d2af8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffca96d2ae8) at ../csu/libc-start.c:325
#17 0x00000000004009e9 in _start ()
(gdb) 

~~~~
